baseURL = "http://nl-a.ru/"
languageCode = "en-us"
title = "NL!A"
theme = "nla"
MetaDataFormat = "toml"
Paginate = 10

[taxonomies]
    tag = "tags"
    coursetag = "coursetags"
    blogtag = "blogtags"


[[menu.main]]
    name = "ПРОДУКТЫ"
    weight = -10
    identifier = "product"
    url = "/post/"
[[menu.main]]
    name = "EduAi"
    weight = -100
    parent = "product"
    identifier = "eduai"
    url = "/eduai/"
[[menu.main]]
    name = "EduQuiz"
    weight = -100
    parent = "product"
    identifier = "eduquiz"
    url = "/eduquiz/"
[[menu.main]]
    name = "МООС \"Основы финансов\""
    weight = -100
    parent = "product"
    identifier = "osnovi_finansov"
    url = "/blog/osnovi_finansov/"
[[menu.main]]
    name = "БЛОГ"
    weight = 10
    url = "/blog/"
[[menu.main]]
    name = "КОМПАНИЯ"
    weight = 12
    url = "/company/"
#[[menu.main]]
#    name = "КУРСЫ"
#    weight = -100
#    url = "/course/"
