baseURL = "http://nl-a.ru/"
languageCode = "en-us"
title = "NL!A"
theme = "nla"
MetaDataFormat = "toml"
Paginate = 10

[taxonomies]
    tag = "tags"
    coursetag = "coursetags"
    blogtag = "blogtags"


[[menu.main]]
    name = "ПРОДУКТЫ"
    weight = -100
    identifier = "product"
    url = "/post/"
[[menu.main]]
    name = "EduAi"
    weight = -100
    parent = "product"
    identifier = "eduai"
    url = "/eduai/"
[[menu.main]]
    name = "БЛОГ"
    weight = -100
    url = "/blog/"
#[[menu.main]]
#    name = "КУРСЫ"
#    weight = -100
#    url = "/course/"
